### ISSUE TITLE
Errors in hunuj.conf

### ISSUE THREAD

**Issue by DavidHaslam** [krisek/HunUj#1]
The following line in `hunuj.conf` uses an obsolete key.
`OSISqToTick=false`
_It should be removed_.

The following lines should have been updated.
`MinimumVersion=1.6.0`
`SwordVersionDate=2012-03-11`
`Version=1.7`

They should match the **German** v11n and the latest module update and read:
`MinimumVersion=1.6.1`
`SwordVersionDate=2020-03-01`
`Version=1.8`

The following three **history** lines seem to have been removed:
`History_1.7.3=Corrected .conf encoding (2013-08-21)`
`History_1.7.2=Added OSISFootnotes filter to configuration file (2012-04-17)`
`History_1.7.1=Corrected typos in configuration file (2012-04-04)`
_They should be re-instated_.

The single **Description** key should be replaced by these two keys.
`Description=Magyar Bibliatársulat újfordítású Bibliája`
`Description_en=The New Translation Bible of the Hungarian Bible Society`

The following key has no argument.
`DistributionNotes=`
_Either remove it or provide suitable notes_.

**Comment by DavidHaslam** [comment]
[hunuj.zip](https://github.com/krisek/HunUj/files/4281639/hunuj.zip)

_I attach the old config file simply for reference_.

**Comment by krisek** [comment]
Many thanks for pointing them out, fixed in [1ba7bde](https://github.com/krisek/HunUj/commit/1ba7bde2c54fdadc70e71214bdcfcb087b9750a8)
Please check so that we can close.

**Comment by DavidHaslam** [comment]
We should have this in **hunuj.conf**

`TextSource=szentiras.hu/UF`

But to be truly authentic, all 1189 chapter pages should be scraped from the above site and reconverted to a new single OSIS file.

We should not use the Git repository as the configured URL for the module text source.
This is merely a place for collaborative module development.
It's not the authoritative and authentic digital source of the published 1990 revision of the translation.

**Comment by krisek** [comment]
Unfortunately this is beyond the scope of this activity.
