### ISSUE TITLE
17 verses with no text ?

### ISSUE THREAD

**Issue by DavidHaslam** [krisek/HunUj#2]
The following verse elements in the OSIS XML file have no verse text and should be reviewed.

          <verse osisID="Num.29.40"></verse>
          <verse osisID="2Kgs.16.20"></verse>
          <verse osisID="Job.41.27"></verse>
          <verse osisID="Job.41.28"></verse>
          <verse osisID="Job.41.29"></verse>
          <verse osisID="Job.41.30"></verse>
          <verse osisID="Job.41.31"></verse>
          <verse osisID="Job.41.32"></verse>
          <verse osisID="Job.41.33"></verse>
          <verse osisID="Job.41.34"></verse>
          <verse osisID="Ezek.20.45"></verse>
          <verse osisID="Ezek.20.46"></verse>
          <verse osisID="Ezek.20.47"></verse>
          <verse osisID="Ezek.20.48"></verse>
          <verse osisID="Ezek.20.49"></verse>
          <verse osisID="Acts.19.41"></verse>
          <verse osisID="2Cor.13.14"></verse>

- How does this reflect the **German** versification (if at all) ?
- Is there any part of the translation still missing?

**Comment by krisek** [comment]
I don't know if this is the German versification or the Hungarian translation itself, but these verses don't appear in printed editions either.

**Comment by DavidHaslam** [comment]
The 17 empty verse tags may be safely deleted from the OSIS file.
