### ISSUE TITLE
Change path for osisCore.2.1.1.xsd

### ISSUE THREAD

**Issue by DavidHaslam** [krisek/HunUj#4]
The **bibletechnologies.net** website ceased to exist some years back.

Line 6 in the file `hunuj.osis.xml` could be sensibly changed to
```
        xsi:schemaLocation="http://www.bibletechnologies.net/2003/OSIS/namespace https://www.crosswire.org/osis/osisCore.2.1.1.xsd">
```
This enables validation from within text editors such as **Notepad++** via the **XMLTools** plugin.

**Comment by krisek** [comment]
fixed with d9ceb24
