### ISSUE TITLE
XML file still contains 1 control character \x92 in Mark.13.14

### ISSUE THREAD

**Issue by DavidHaslam** [krisek/HunUj#5]
The recent edit failed to remove `\x92` from Mark.13.14
```
            <verse osisID="Mark.13.14">„Amikor pedig meglátjátok a ’pusztító utálatosságot’ ott állni, ahol nem volna szabad - aki olvassa, értse meg! -, akkor, akik Júdeában vannak, meneküljenek a hegyekbe,<note osisID="Mark.13.14!crossReference.d" n="d" osisRef="Mark.13.14" type="crossReference">
                <reference osisRef="Dan.9.27">Dán 9:27</reference>;
                <reference osisRef="Dan.11.31">Dán 11:31</reference>;
                <reference osisRef="Dan.12.11">Dán 12:11</reference>
              </note>
            </verse>
```
The delinquent control character **PU2** appears at the end of this quoted phrase:
```
’pusztító utálatosságot’
```
It should be removed!

Moreover, both the single quotation marks are  right handed: **U+2019**.
IMHO, the leading one should be left handed: **U+2018**.

**Comment by DavidHaslam** [comment]
Detected again using **BabelPad Tools | Character Frequency**:

[Analysis.zip](https://github.com/krisek/HunUj/files/4809837/Analysis.zip)

**Comment by DavidHaslam** [comment]
Also arising from the character count:

**Jer.31.18** section title contains a strange character sequence `[+-` 
```
          <div type="section"><title subType="x-preverse">Efraim bűnbánata [+- Isten irgalmassága</title>
```
_It is probably spurious._

**Comment by DavidHaslam** [comment]
**Another query**: The section title before **Ps.90.1** ends with a circumflex accent!
```
            <div type="section"><title subType="x-preverse">Az örökkévaló Isten és a mulandó ember^</title>
```
_Looks suspicious._

**Comment by krisek** [comment]
fixed all with c590162

So much appreciated! Many thaks

I realized now that quotation marks are inconsistent in the text, won't fix for known reasons

**Comment by DavidHaslam** [comment]
That was quick!

FYI. I've since added the word frequency results to the **Analysis** folder.

[Analysis.zip](https://github.com/krisek/HunUj/files/4809886/Analysis.zip)

**Comment by DavidHaslam** [comment]
FYI. The word count has been pasted into Excel and sorted.

Further analysis may help with Hungarian spell checking.

[HunUj OSIS XML Word Count.xlsx](https://github.com/krisek/HunUj/files/4809905/HunUj.OSIS.XML.Word.Count.xlsx)
